
#Client side configurations for the mod. Modpacks should not ship non-default versions of this file!
[client]
	#Whether or not the growth animation should be played.
	useGrowthAnimation = false
	#Whether or not the soil in pots should be rendered.
	renderSoil = false
	#Whether or not crops should render in pots.
	renderCrop = false
	#Whether or not break effects should occur when harvested.
	breakEffects = false

